[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff"]

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format" }
